export const jobData = [
  {
    id: 1,
    title: "Senior Software Engineer",
    Salary: "$180k",
    description:
      "We are looking for a skilled Full Stack Engineer proficient in React and Node.js to join our dynamic team.",
    responsibilities: [
      "Develop and maintain scalable web applications.",
      "Collaborate with designers, product managers, and engineers.",
      "Write clean, maintainable, and efficient code.",
      "Optimize applications for performance and scalability.",
      "Ensure best practices in software engineering and security.",
    ],
    skills: [
      "Experience with React.js, Node.js, and Express.js.",
      "Experience with RESTful APIs and GraphQL.",
      "Experience with MongoDB and PostgreSQL.",
      "Experience with AWS, Docker, and Kubernetes.",
      "Experience with CI/CD pipelines and Git.",
    ],
    workMode: "Remote · Full-time",
    time: "10 mins ago",
    country: "United States",
    location: "San Francisco, CA",
  },
  {
    id: 2,
    title: "Senior Frontend Developer",
    Salary: "$150k",
    description:
      "Looking for a React developer with experience in TypeScript, Redux, and Tailwind CSS to build cutting-edge web apps.",
    responsibilities: [
      "Develop responsive user interfaces using React and Tailwind CSS.",
      "Implement state management with Redux and Context API.",
      "Optimize frontend performance for high-speed applications.",
      "Ensure cross-browser compatibility and accessibility.",
      "Collaborate with backend engineers for seamless integration.",
    ],
    skills: [
      "Experience with React.js, Next.js, and TypeScript.",
      "Experience with Redux, Zustand, and Context API.",
      "Experience with Tailwind CSS and Styled Components.",
      "Experience with Jest and React Testing Library.",
      "Experience with REST APIs and WebSockets.",
    ],
    workMode: "Remote · Full-time",
    time: "30 mins ago",
    country: "Canada",
    location: "Toronto, ON",
  },
  {
    id: 3,
    title: "Backend Engineer",
    Salary: "$140k",
    description:
      "Seeking a skilled Node.js developer with expertise in PostgreSQL and GraphQL to work on scalable APIs and microservices.",
    responsibilities: [
      "Design and implement scalable backend architectures.",
      "Develop and maintain RESTful and GraphQL APIs.",
      "Optimize database queries and performance tuning.",
      "Ensure data security and compliance best practices.",
      "Integrate with third-party services and APIs.",
    ],
    skills: [
      "Experience with Node.js, Express.js, and NestJS.",
      "Experience with PostgreSQL, MongoDB, and Redis.",
      "Experience with GraphQL and REST APIs.",
      "Experience with Docker, Kubernetes, and AWS Lambda.",
      "Experience with unit testing using Jest and Mocha.",
    ],
    workMode: "Hybrid · Full-time",
    time: "1 hour ago",
    country: "United Kingdom",
    location: "London",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    Salary: "$120k",
    description:
      "Passionate about designing beautiful interfaces? Join our product team to craft seamless user experiences using Figma and Adobe XD.",
    responsibilities: [
      "Create wireframes, prototypes, and visual designs.",
      "Conduct user research and usability testing.",
      "Collaborate with developers to implement UI components.",
      "Ensure design consistency across the platform.",
      "Optimize user flows for a seamless experience.",
    ],
    skills: [
      "Experience with Figma, Adobe XD, and Sketch.",
      "Experience with user research and usability testing.",
      "Experience with responsive web design.",
      "Experience with design systems and component libraries.",
      "Experience with HTML and CSS (optional).",
    ],
    workMode: "Onsite · Full-time",
    time: "2 hours ago",
    country: "Germany",
    location: "Berlin",
  },
  {
    id: 5,
    title: "Mobile App Developer",
    Salary: "$135k",
    description:
      "Looking for a React Native developer with Expo experience to build and maintain cross-platform mobile applications.",
    responsibilities: [
      "Develop and maintain mobile applications using React Native.",
      "Integrate with backend APIs and third-party services.",
      "Optimize mobile performance for Android and iOS.",
      "Implement push notifications and in-app messaging.",
      "Ensure a smooth and engaging user experience.",
    ],
    skills: [
      "Experience with React Native and Expo.",
      "Experience with JavaScript and TypeScript.",
      "Experience with Redux and React Query.",
      "Experience with Firebase and AWS Amplify.",
      "Experience with mobile UI/UX principles.",
    ],
    workMode: "Remote · Contract",
    time: "3 hours ago",
    country: "Australia",
    location: "Sydney",
  },
  {
    id: 6,
    title: "Data Scientist",
    Salary: "$160k",
    description:
      "We need a Data Scientist with strong Python, TensorFlow, and NLP expertise to work on AI-driven solutions.",
    responsibilities: [
      "Analyze large datasets to derive actionable insights.",
      "Build and optimize machine learning models.",
      "Work with deep learning frameworks like TensorFlow and PyTorch.",
      "Deploy AI models in production environments.",
      "Collaborate with engineers and domain experts.",
    ],
    skills: [
      "Experience with Python, TensorFlow, and PyTorch.",
      "Experience with NLP and Computer Vision.",
      "Experience with SQL, Pandas, and NumPy.",
      "Experience with data visualization using Matplotlib and Seaborn.",
      "Experience with AWS, Google Cloud, and Azure AI.",
    ],
    workMode: "Hybrid · Full-time",
    time: "4 hours ago",
    country: "India",
    location: "Bangalore",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    Salary: "$145k",
    description:
      "Help us scale our infrastructure by managing CI/CD pipelines, Docker, and AWS deployments.",
    responsibilities: [
      "Automate deployment pipelines for cloud infrastructure.",
      "Manage Kubernetes clusters and containerized applications.",
      "Monitor and optimize system performance.",
      "Implement security best practices for cloud environments.",
      "Collaborate with developers to ensure smooth deployments.",
    ],
    skills: [
      "Experience with AWS, Azure, and Google Cloud.",
      "Experience with Docker and Kubernetes.",
      "Experience with Terraform and Ansible.",
      "Experience with CI/CD using Jenkins and GitHub Actions.",
      "Experience with monitoring tools like Prometheus and Grafana.",
    ],
    workMode: "Remote · Full-time",
    time: "5 hours ago",
    country: "Netherlands",
    location: "Amsterdam",
  },
  {
    id: 8,
    title: "Product Manager",
    Salary: "$170k",
    description:
      "Seeking an experienced Product Manager to drive roadmap and execution for our SaaS platform.",
    responsibilities: [
      "Define and manage product roadmap and strategy.",
      "Work closely with engineering, design, and marketing teams.",
      "Conduct market research to identify user needs.",
      "Measure product performance and optimize accordingly.",
      "Lead agile product development cycles.",
    ],
    skills: [
      "Experience with product strategy and agile methodologies.",
      "Experience with market research and A/B testing.",
      "Experience with user analytics using Google Analytics and Mixpanel.",
      "Experience with wireframing and prototyping.",
      "Experience with stakeholder communication.",
    ],
    workMode: "Onsite · Full-time",
    time: "6 hours ago",
    country: "United States",
    location: "New York, NY",
  },
  {
    id: 9,
    title: "Cybersecurity Analyst",
    Salary: "$155k",
    description:
      "Protect our company from cyber threats. Work with SIEM tools, penetration testing, and security policies.",
    responsibilities: [
      "Monitor and respond to security incidents.",
      "Conduct vulnerability assessments and penetration testing.",
      "Implement security policies and best practices.",
      "Train employees on cybersecurity awareness.",
      "Ensure compliance with data protection regulations.",
    ],
    skills: [
      "Experience with SIEM tools like Splunk and QRadar.",
      "Experience with penetration testing and ethical hacking.",
      "Experience with network security and firewalls.",
      "Experience with incident response and threat hunting.",
      "Experience with compliance standards like GDPR and ISO 27001.",
    ],
    workMode: "Remote · Full-time",
    time: "8 hours ago",
    country: "Singapore",
    location: "Singapore",
  },
];
